RNP-master/ModulosCoreMvc/Areas/Seguridad/Controllers/UsuariosController.cs
using Modulos_Core_MVC.Security;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SERFOR.Component.SeguridadCore.DataAccess;
using SERFOR.Component.Tools.Cryptography;
using SERFOR.Component.DTEntities.Seguridad;
using SERFOR.Component.SeguridadCore.BusinessLogic.Facade;
using Newtonsoft.Json;

namespace Modulos_Core_MVC.Areas.Seguridad.Controllers
{
    [Authorize(Roles = "ADMINSIS")]
    public class UsuariosController : Controller
    {
        private SecuritySchema db = new SecuritySchema();

        // GET: Seguridad/Usuarios
        public ActionResult Index()
        {
            ViewBag.RoleName = GetRol();
            var usuario = db.Usuario.Include(u => u.Persona);
            return View(usuario.ToList());
        }

        public ContentResult GetAllUsuarios()
        {
            string json = JsonConvert.SerializeObject(UsuarioFacade.GetAll());
            return Content(json);
        }

        // GET: Seguridad/Usuarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Seguridad/Usuarios/Create
        public ActionResult Create()
        {
            UsuarioTableRowDTe usuario = null;

            usuario = new UsuarioTableRowDTe() { Id = 0 };
            ViewBag.RoleName = GetRol();
            return View(usuario);
        }
    // POST: Seguridad/Usuarios/Create
    // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
    // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
    /*[HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Usuario_Id,Nombre,Clave,Activo,FechaInicio,FechaFin,Sede_Id,SedePrincipal_Id,EsSedePrincipal,UsuarioCreacion,FechaCreacion,UsuarioModificacion,FechaModificacion")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.Clave = HashCrypter.Sha1Encrypter(usuario.Clave);
                usuario.FechaCreacion = DateTime.Today;
                usuario.FechaModificacion = DateTime.Today;
                db.Usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Usuario_Id = new SelectList(db.Persona, "Id", "Nombres", usuario.Usuario_Id);
            return View(usuario);
        }*/
        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            bool rspta = false;
            string mensaje = string.Empty;
            try
            {
                var usuario = new UsuarioTableRowDTe();
                usuario.NombreUsuario = form["nombreUsuario"];
                usuario.Password = HashCrypter.Sha1Encrypter(form["clave"]);
                usuario.Id = Convert.ToInt32(form["PersonaList"]);
                DateTime fechaIni;
                if (!string.IsNullOrEmpty(form["FechaInicio"]) && DateTime.TryParse(form["FechaInicio"], out fechaIni))
                    usuario.FechaInicio = fechaIni;
                DateTime fechaFin;
                if (!string.IsNullOrEmpty(form["FechaFinal"]) && DateTime.TryParse(form["FechaFinal"], out fechaFin))
                    usuario.FechaFin = fechaFin;

                usuario.Sede_Id = Convert.ToByte(form["Sede"]);
                usuario.SedePrincipal_Id = Convert.ToByte(form["SedePrincipal"]);

                bool essedeprincipal = Convert.ToBoolean(form["EsSedePrincipal"]);
                usuario.EsSedePrincipal = essedeprincipal;

                usuario.UsuarioModifica = UserInfo.GetUserName();

                if (form["Roles"] != null) { 
                string roles = form["Roles"];

                string[] lst_roles = roles.Split(',');
                foreach (string rol in lst_roles)
                {
                    RolDTe r = new RolDTe();
                    r.Id = byte.Parse(rol);
                    usuario.Roles.Add(r);
                }
            }
                usuario.Directorio.Cargo_Id = Convert.ToInt16(form["Cargo"]);
                usuario.Directorio.Sede_Id = Convert.ToByte(form["Sede"]);
                usuario.Directorio.Persona_Id = Convert.ToInt32(form["PersonaList"]);
                usuario.Directorio.Email = form["Email"];
                bool esresponsable = Convert.ToBoolean(form["EsResponsable"]);
                usuario.Directorio.EsResponsable = esresponsable;
                rspta = UsuarioFacade.Insert(usuario);

                //id = (Convert.ToInt32(form["Id"]) == 0) ? PersonaFacade.Insert(persona) : PersonaFacade.Update(Convert.ToInt32(form["Id"]), persona);


            }
            catch (Exception ex)
            {
                mensaje = ex.Message;
            }
            return Json(new { success = rspta, responseText = mensaje, innerId = form["PersonaList"] }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int? id)
        {
            int id2 = id ?? 0;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsuarioTableRowDTe usuario = UsuarioFacade.GetRowById(id2);

            if (usuario == null)
            {
                return HttpNotFound();
            }
            usuario.Password = "";
            ViewBag.Usuario_Id = new SelectList(db.Persona, "Id", "Nombres", usuario.Persona.Id);
            ViewBag.Sede_Id = new SelectList(db.SedeAutoridadForestal, "Id", "Nombre", usuario.Sede_Id);
            ViewBag.SedePrincipal_Id = new SelectList(db.SedeAutoridadForestal, "Id", "Nombre", usuario.SedePrincipal_Id);
            ViewBag.RoleName = GetRol();
            return View(usuario);
        }

        [HttpPost]
        public ActionResult Update(FormCollection form)
        {
            bool rspta = false;
            string mensaje = string.Empty;
            try
            {
                var usuario = new UsuarioTableRowDTe();
                usuario.NombreUsuario = form["nombreUsuario"];
                if(form["clave"].Length>0) usuario.Password = HashCrypter.Sha1Encrypter(form["clave"]);
                usuario.Id = Convert.ToInt32(form["Id"]);
                DateTime fechaIni;
                if (!string.IsNullOrEmpty(form["FechaInicio"]) && DateTime.TryParse(form["FechaInicio"], out fechaIni))
                    usuario.FechaInicio = fechaIni;
                DateTime fechaFin;
                if (!string.IsNullOrEmpty(form["FechaFinal"]) && DateTime.TryParse(form["FechaFinal"], out fechaFin))
                    usuario.FechaFin = fechaFin;

                usuario.Sede_Id = Convert.ToByte(form["Sede"]);
                usuario.SedePrincipal_Id = Convert.ToByte(form["SedePrincipal"]);

                bool essedeprincipal = Convert.ToBoolean(form["EsSedePrincipal"]);
                usuario.EsSedePrincipal = essedeprincipal;

                usuario.UsuarioModifica = UserInfo.GetUserName();

                if (form["Roles"] != null)
                {
                    string roles = form["Roles"];

                    string[] lst_roles = roles.Split(',');
                    foreach (string rol in lst_roles)
                    {
                        RolDTe r = new RolDTe();
                        r.Id = byte.Parse(rol);
                        usuario.Roles.Add(r);
                    }
                }
                usuario.Directorio.Cargo_Id = Convert.ToInt16(form["Cargo"]);
                usuario.Directorio.Sede_Id = Convert.ToByte(form["Sede"]);
                usuario.Directorio.Persona_Id = Convert.ToInt32(form["Id"]);
                usuario.Directorio.Email = form["Email"];
                bool esresponsable = Convert.ToBoolean(form["EsResponsable"]);
                usuario.Directorio.EsResponsable = esresponsable;
                //rspta = UsuarioFacade.Insert(usuario);
                rspta = UsuarioFacade.Update(Convert.ToInt32(form["Directorio_Id"]), form["Roles"], usuario);

                //id = (Convert.ToInt32(form["Id"]) == 0) ? PersonaFacade.Insert(persona) : PersonaFacade.Update(Convert.ToInt32(form["Id"]), persona);
            }
            catch (Exception ex)
            {
                mensaje = ex.Message;
            }
            return Json(new { success = rspta, responseText = mensaje, innerId = form["Id"] }, JsonRequestBehavior.AllowGet);
        }

        // GET: Seguridad/Usuarios/Delete/5
      /*  public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }*/

        [HttpPost]
        public JsonResult Delete(int id)
        {
            ViewBag.RoleName = GetRol();
            return Json(UsuarioFacade.DeleteById(id));
        }

        // POST: Seguridad/Usuarios/Delete/5
       /* [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuario.Find(id);
            db.Usuario.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }*/

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

RNP-master/ModulosCoreMvc/Areas/Seguridad/Views/Usuarios/Delete.cshtml
@model SERFOR.Component.SeguridadCore.DataAccess.Usuario

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Seguridad/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Usuario</h2>

<h3>Está seguro que quiere eliminarlo?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Clave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sede_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sede_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SedePrincipal_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SedePrincipal_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EsSedePrincipal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EsSedePrincipal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioModificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaModificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persona.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persona.Nombres)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Retornar a Listado", "Index")
        </div>
    }
</div>

RNP-master/ModulosCoreMvc/Areas/Seguridad/Views/Usuarios/Details.cshtml
@model SERFOR.Component.SeguridadCore.DataAccess.Usuario

@{
    ViewBag.Title = "Registro de Usuario";
    Layout = "~/Areas/Seguridad/Views/Shared/_Layout.cshtml";
}

<h2>Ver</h2>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Persona.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persona.Nombres)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sede_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sede_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SedePrincipal_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SedePrincipal_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EsSedePrincipal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EsSedePrincipal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioModificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaModificacion)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Usuario_Id }) |
    @Html.ActionLink("Retornar a Listado", "Index")
</p>

RNP-master/ModulosCoreMvc/Areas/Seguridad/Views/Usuarios/Index.cshtml
@{
    ViewBag.Title = "Gestión de Usuarios";
    Layout = "~/Areas/Seguridad/Views/Shared/_Layout.cshtml";
}

<h3>
    Gestión de Usuarios
    <a type="button" class="btn btn-success  pull-right" href="@Url.Action("Create", "Usuarios", new { area = "Seguridad" })">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Registrar
    </a>
</h3>
<div class='hr'></div>

@using (Html.BeginForm())
{
    <table id="table"
           data-unique-id="Id"
           data-classes="table-bordered"
           @*data-side-pagination="server"
           data-url='@Url.Action("GetPersonas", "Persona", new { area = "General" })'
            data-query-params-type="Else"*@
           data-side-pagination="client"
           data-url='@Url.Action("GetAllUsuarios", "Usuarios", new { area = "Seguridad" })'
           data-show-pagination-switch="true"
           data-pagination="true"
           data-page-size="20"
           data-page-list="[15,20, 30, 50, 100]"
           data-search="true"
           data-toggle="table"
           data-show-columns="true"
           data-show-refresh="true"
           data-show-export="true"
           data-show-toggle="true"
           data-mobile-responsive="true"
           data-show-footer="false"
           data-click-to-select="true"
           data-single-select="true"
           data-striped="true"
           @*data-toolbar="#toolbar"*@
           data-show-multi-sort="false">
        <thead>
            <tr>

                <th data-halign="center" data-align="center" data-valign="center" style="width:70px" data-formatter="optionFormatter">Opción</th>
                <th data-field="Id" data-halign="center" data-align="right" data-sortable="true" style="width:50px">
                    ID
                </th>
                <th data-field="NombreUsuario" data-halign="center" data-align="center" data-sortable="true" class="col-md-2">
                    Usuario
                </th>
                <th data-field="NombreCompleto" data-halign="center" data-align="center" data-sortable="true" class="col-md-3">
                    Persona asociada
                </th>
                <th data-field="FechaInicio" data-halign="center" data-sortable="false" class="col-md-2">
                    Fecha Inicio
                </th>
                <th data-field="FechaFin" data-halign="center" data-sortable="false" class="col-md-2">
                    Fecha Fin
                </th>
                <th data-field="Sede" data-halign="center" data-sortable="true" class="col-md-2">
                    Sede
                </th>
                <th data-field="SedePrincipal" data-halign="center" data-sortable="true" class="col-md-2">
                    Sede Principal
                </th>
                <th data-field="EsSedePrincipal" data-halign="center" data-align="center" data-valign="center" data-sortable="true" data-formatter="checkFormatter" class="col-md-1">
                    Es Sede Principal?
                </th>
            </tr>
        </thead>
        <tbody id="entityListBody"></tbody>
    </table>
}



<!-- Modal para mostrar la información de detalle de la persona seleccionada -->
<div class="modal fade" id="modalDetallesPersona" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div id="bodyDetails" class="modal-body" style="padding:5px">

            </div>
            <div class="modal-footer" style="padding:5px">
                <a id="btnEdit" href='#' class="btn btn-success pull-left">Editar</a>
                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script type="text/javascript">
        function optionFormatter(value, row) {
            return '<div class="btn-group btn-group-xs" role="group" aria-label="...">' +
                    '<a href="/Seguridad/Usuarios/Edit?id=' + row.Id + '" type="button" class="btn btn-default"c><span class="glyphicon glyphicon-edit"></span></a>' +
                    '<a href="#" type="button" class="btn btn-danger" onClick="confirmDelete(' + row.Id + ')"><span class="glyphicon glyphicon-trash"></span></a>' +
                   '</div>';

        }

        function detailFormatter(value, row) {
            return '<a href="#" onClick = "modalDetalles(' + row.Id + ')">' + value + '</a>'
        }

        function modalDetalles(id) {
            $('#bodyDetails').empty();

            $.ajax({
                method: "GET",
                url: '@Url.Action("_DetailsPopUp", "Persona", new { area = "General"})',
                data: { id: id },
                cache: false,
                success: function (data) {
                    $('#modalDetallesPersona').modal('show');
                    $('#bodyDetails').html(data);
                    $('#btnEdit').attr('href', '/Persona/Edit?id=' + id);
                },
                error: function (ex) {
                    showNotification(constantes.tipoAlerta.DANGER, "¡Algo salió mal!", "Ocurrió un error al intentar mostrar la información de la persona seleccionada." + ex);
                }
            });
        }

        function confirmDelete(id) {

            bootbox.confirm({
                message: "El Usuario seleccionado con ID " + id + ", será eliminada. !Esta seguro?",
                buttons: {
                    confirm: {
                        label: '<i class="glyphicon glyphicon-remove"></i>&nbsp;Eliminar',
                        className: 'btn-danger'
                    },
                    cancel: {
                        label: 'Cancelar',
                        className: 'btn-default'
                    }
                },
                callback: function (result) {
                    if (result) {
                        $.ajax({
                            url: '@Url.Action("Delete", "Usuarios", new { area = "Seguridad"})',
                            method: "POST",
                            data: { id: id },
                            dataType: 'json',
                            success: function (result) {
                                if (result) {
                                    $('#table').bootstrapTable('removeByUniqueId', id);
                                    showNotification(constantes.tipoAlerta.SUCCESS, "¡En hora Buena!", " El registro seleccionado fue eliminado correctamente. ");
                                }
                                else {
                                    showNotification(constantes.tipoAlerta.DANGER, "¡Algo salió mal!",
                                        "Ocurrió un error al intentar eliminar a la persona seleccionada. Es problable que el registro esté asociado a una plantación o a un usuario del sistema.");
                                }
                            },
                            error: function () {

                            }
                        });
                    }
                }
            });

            return false;
        }

    </script>

}