RNP-master/ModulosCoreMvc/Areas/Plantaciones/Controllers/RNPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modulos_Core_MVC.Security;
using SERFOR.Component.DTEntities.Plantaciones;
using SERFOR.Component.PlantacionCore.BusinessLogic.Facade;

namespace Modulos_Core_MVC.Areas.Plantaciones.Controllers
{
    [Authorize(Roles = "ADMINSIS,ADMINPLNT,ESPFORDIR,ESPATFFS,ESPCATAST,CONSULTOR")]
    public class RNPController : Controller
    {
        // GET: Plantaciones/RNP
        public ActionResult Index()
        {
            ViewBag.RoleName = GetRol();
            return View();
        }
        private string GetRol()
        {
            String result = "";
            if (User.IsInRole("CONSULTOR")) result = "CONSULTOR";
            if (User.IsInRole("REGISTRADOR")) result = "REGISTRADOR";
            if (User.IsInRole("ESPATFFS")) result = "ESPATFFS";
            if (User.IsInRole("ESPFORDIR")) result = "ESPFORDIR";
            if (User.IsInRole("ESPCATAST")) result = "ESPCATAST";
            if (User.IsInRole("ADMINPLNT")) result = "ADMINPLNT";
            if (User.IsInRole("ADMINSIS")) result = "ADMINSIS";
            return result;
        }
        public JsonResult GetRNP(string order, string offset = "-1", string limit = "-1", string search = "", string sort = "")
        {
            //IEnumerable<PlantacionItemListDTe> list = new List<PlantacionItemListDTe>();
            Resultado res = new Resultado();

            if (User.IsInRole("ESPFORDIR") || User.IsInRole("ESPCATAST") || User.IsInRole("ADMINPLNT"))
            {
                res = PlantacionFacade.GetRNP(order, int.Parse(offset), int.Parse(limit), search, sort);
            }
            else
            {
                if (User.IsInRole("ESPATFFS") || User.IsInRole("REGISTRADOR") || User.IsInRole("CONSULTOR"))
                {
                    res = PlantacionFacade.GetRNPBySedeId(UserInfo.GetSedeId().Value, UserInfo.GetEsSedePrincipal().Value, order, int.Parse(offset), int.Parse(limit), search, sort);
                }
            }

            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize(Roles = "ADMINPLNT,ESPATFFS")]
        public JsonResult Anular(int id)
        {
            bool rspta = PlantacionFacade.AnularById(id, UserInfo.GetUserName());
            if (rspta)
            {
                InsertHistorico(id);
            }
            return Json(rspta);

        }

        [HttpPost]
        public JsonResult InsertHistorico(int id)
        {
            return Json(HistoricoFacade.InsertByPlantacionId(id, UserInfo.GetUserName()));
        }
    }
}

RNP-master/ModulosCoreMvc/Areas/Plantaciones/Controllers/ReportesController.cs
using SERFOR.Component.PlantacionCore.BusinessLogic.Facade;
using System.Web.Mvc;

namespace Modulos_Core_MVC.Areas.Plantaciones.Controllers
{
    [Authorize(Roles = "ADMINSIS,ADMINPLNT,ESPFORDIR,ESPCATAST,ESPATFFS,CONSULTOR")]
    public class ReportesController : Controller
    {
        // GET: Plantaciones/Reportes
        public ActionResult IndexMINAGRI()
        {            
            return View();
        }

        // GET: Plantaciones/Reportes
        public ActionResult IndexSummary()
        {
            return View();
        }


        public ActionResult ReportOficial()
        {
            ViewBag.RoleName = GetRol();
            return View();
        }

        public JsonResult GetPlantaciones(string codigoDepartamento)
        {
            return Json(ReportesFacade.GetApprovedByDepartment(true, codigoDepartamento), JsonRequestBehavior.AllowGet);
        }

        

        public ActionResult ReportDepartment()
        {
            ViewBag.RoleName = GetRol();
            return View();
        }

        public JsonResult GetDataDepartamentos()
        {
            return Json(ReportesFacade.GetDataDepartments(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ReportSummary()
        {
            ViewBag.RoleName = GetRol();
            return View();

        }
        public ActionResult ReportResumen()
        {
            ViewBag.RoleName = GetRol();
            return View();
        }
        public ActionResult ReportAreaPlantacion()
        {
            ViewBag.RoleName = GetRol();
            return View();
        }
        public JsonResult GetAllPlantaciones(bool soloAprobados, char condicion, string codigoDepartamento)
        {
            return Json(ReportesFacade.GetSummaryByFilter(soloAprobados, condicion, codigoDepartamento), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetResumenPlantaciones()
        {
            JsonResult result = Json(ReportesFacade.GetResumenPlantacion(), JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = 50000000;
            return result;            

        }
        public JsonResult GetResumenPlantacionEspacio()
        {
            JsonResult result = Json(ReportesFacade.GetResumenPlantacionEspacio(), JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = 50000000;
            return result;

        }
        public JsonResult GetResumenPlantacionProduccion()
        {
            JsonResult result = Json(ReportesFacade.GetResumenPlantacionProduccion(), JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = 50000000;
            return result;

        }
        private string GetRol()
        {
            string result = "";
            if (User.IsInRole("CONSULTOR")) result = "CONSULTOR";
            if (User.IsInRole("REGISTRADOR")) result = "REGISTRADOR";
            if (User.IsInRole("ESPATFFS")) result = "ESPATFFS";
            if (User.IsInRole("ESPFORDIR")) result = "ESPFORDIR";
            if (User.IsInRole("ESPCATAST")) result = "ESPCATAST";
            if (User.IsInRole("ADMINPLNT")) result = "ADMINPLNT";
            if (User.IsInRole("ADMINSIS")) result = "ADMINSIS";
            return result;
        }
    }
}

RNP-master/ModulosCoreMvc/Areas/Inventario/Views/Shared/_Layout.cshtml
@using Modulos_Core_MVC.Helpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="width:100%; height: 100%; margin:0px">
    @RenderBody()
</div>


@section menu{
    <li><a href="@Url.Action("Create", "Interesado", new { area= "Plantaciones", id = 0})">INGRESO DE<strong>INTERESADO</strong></a></li>
    <li><a href="@Url.Action("Index", "Interesado", new { area= "Plantaciones"})">GESTIÓN DE<strong>INTERESADOS</strong></a></li>
    <li><a href="@Url.Action("Create", "Plantacion", new { area= "Plantaciones", id = 0})">INGRESO DE<strong>PLANTACIÓN</strong></a></li>
    <li><a href="@Url.Action("Index", "Plantacion", new { area= "Plantaciones"})">GESTIÓN DE<strong>PLANTACIONES</strong></a></li>
    <li><a href="@Url.Action("Index", "RNP", new { area= "Plantaciones"})">REGISTRO NACIONAL<strong>DE PLANTACIONES</strong></a></li>

    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">
            REPORTES DE
            <span class="caret"></span>
            <strong>PLANTACIONES</strong>
        </a>
        <ul class="dropdown-menu">
            <li><a href="@Url.Action("ReportSummary", "Reportes", new { area= "Plantaciones"})">Resumen de Plantaciones (Dashboard mode)</a></li>
            <li><a href="@Url.Action("ReportDepartment", "Reportes", new { area= "Plantaciones"})">Información por Departamento</a></li>
            <li><a href="@Url.Action("ReportOficial", "Reportes", new { area= "Plantaciones"})">Lista oficial de Plantaciones</a></li>
            <li class="divider"></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">Reportes Dinámicos<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="https://app.powerbi.com/view?r=eyJrIjoiMDg2NTY1MDQtYzhhNy00NTJiLTgyNTEtZmM5Y2RlNjdlMzI2IiwidCI6IjY4ZjZmMjRjLTA4YjktNGQxYS05MzMxLTFkMTE3ZjU0ZGE5NyIsImMiOjR9"
                           target="_blank">Número de Plantaciones y Área Plantada por Departamento</a>
                    </li>
                    <li>
                        <a href="https://app.powerbi.com/view?r=eyJrIjoiMmI1ODc4MDYtMmY4Yy00YTFkLTkzOGUtN2NmZjAyN2M2MzBkIiwidCI6IjY4ZjZmMjRjLTA4YjktNGQxYS05MzMxLTFkMTE3ZjU0ZGE5NyIsImMiOjR9"
                           target="_blank">MINAGRI - Detalle de Plantaciones</a>
                    </li>
                    <li>
                        <a href="https://app.powerbi.com/view?r=eyJrIjoiNTVlNjJhNGEtNjU5NS00ZDZlLThhMjQtMGM5MmM5M2NjODlkIiwidCI6IjY4ZjZmMjRjLTA4YjktNGQxYS05MzMxLTFkMTE3ZjU0ZGE5NyIsImMiOjR9"
                           target="_blank">Línea de tiempo - Área plantada y Número de plantaciones</a>
                    </li>
                    <li>
                        <a href="https://app.powerbi.com/view?r=eyJrIjoiYzFlNDkzM2ItOGI2Ny00MWEwLTkwYmMtMDRlNTQyNzMwY2NiIiwidCI6IjY4ZjZmMjRjLTA4YjktNGQxYS05MzMxLTFkMTE3ZjU0ZGE5NyIsImMiOjR9"
                           target="_blank">Detalle de Plantaciones - Ubicación Geográfica</a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>

    <li>
        <a id="helpButton" type="submit" target="_blank"
           style="width:55px;height: 55px;padding:5px 5px;font-size:40px;line-height:1.33;border-radius:35px;"
           href="//e.issuu.com/embed.html#30236279/50566019" class="btn btn-default btn-circle btn-xl"><i class="glyphicon glyphicon-question-sign"></i></a>
    </li>
}


@section scripts{

    @Html.RenderScripts()
    @RenderSection("scripts", required: false)

}